import java.awt.Color;
import javax.swing.JFrame;
import java.lang.Object;

public class TurtleGuy
{
    public static void main(String args[])
    
    {
        World turtleWorld = new World();
        Turtle turtleOne = new Turtle(330,400,turtleWorld);
        Turtle turtleTwo = new Turtle(330,400,turtleWorld);
        Turtle turtleThree = new Turtle(20,20,turtleWorld);
        Picture background = new Picture("yellow.jpg");
        turtleWorld.setPicture(background);
        turtleOne.setWidth(40);
        turtleOne.setHeight(40);
        turtleOne.setShellColor(Color.BLACK);
        turtleTwo.setShellColor(Color.RED);
        turtleThree.penDown();
        turtleThree.setPenColor(Color.RED);
        turtleThree.turn(90);
        turtleThree.forward(40);
        turtleThree.turn(90);
        turtleThree.forward(100);
        turtleThree.turn(180);
        turtleThree.forward(100);
        turtleThree.turn(90);
        turtleThree.forward(40);
        turtleThree.penUp();
        turtleThree.forward(20);
        turtleThree.penDown();
        turtleThree.forward(40);
        turtleThree.turn(90);
        turtleThree.forward(40);
        turtleThree.turn(90);
        turtleThree.forward(40);
        turtleThree.turn(90);
        turtleThree.forward(40);
        turtleThree.turn(180);
        turtleThree.forward(80);
        turtleThree.turn(180);
        turtleThree.forward(40);
        turtleThree.turn(135);
        turtleThree.forward(50);
        turtleThree.turn(180);
        turtleThree.forward(50);
        turtleThree.turn(45);
        turtleThree.forward(40);
        turtleThree.penUp();
        turtleThree.turn(90);
        turtleThree.forward(60);
        turtleThree.penDown();
        turtleThree.forward(40);
        turtleThree.turn(180);
        turtleThree.forward(40);
        turtleThree.turn(270);
        turtleThree.forward(40);
        turtleThree.turn(270);
        turtleThree.forward(40);
        turtleThree.turn(180);
        turtleThree.forward(40);
        turtleThree.turn(270);
        turtleThree.forward(40);
        turtleThree.turn(270);
        turtleThree.forward(40);
        turtleThree.penUp();
        turtleThree.turn(270);
        turtleThree.forward(80);
        turtleThree.turn(90);
        turtleThree.forward(20);
        turtleThree.penDown();
        turtleThree.forward(40);
        turtleThree.turn(180);
        turtleThree.forward(40);
        turtleThree.turn(270);
        turtleThree.forward(40);
        turtleThree.turn(270);
        turtleThree.forward(40);
        turtleThree.turn(180);
        turtleThree.forward(40);
        turtleThree.turn(270);
        turtleThree.forward(40);
        turtleThree.turn(270);
        turtleThree.forward(40);
        turtleOne.setPenColor(Color.darkGray);
        turtleTwo.setPenColor(Color.darkGray);
        turtleOne.penDown();
        turtleTwo.penDown();
        turtleOne.turn(90);
        turtleTwo.turn(270);
        turtleOne.forward(50);
        turtleTwo.forward(50);
        turtleOne.turn(270);
        turtleTwo.turn(90);
        turtleOne.forward(100);
        turtleTwo.forward(100);
        turtleOne.setPenColor(Color.GREEN);
        turtleTwo.setPenColor(Color.GREEN);
        turtleOne.turn(90);
        turtleTwo.turn(270);
        turtleOne.forward(50);
        turtleTwo.forward(50);
        turtleOne.turn(330);
        turtleTwo.turn(30);
        turtleOne.forward(50);
        turtleTwo.forward(50);
        turtleOne.turn(330);
        turtleTwo.turn(30);
        turtleOne.forward(50);
        turtleTwo.forward(50);
        turtleOne.turn(330);
        turtleTwo.turn(30);
        turtleOne.forward(50);
        turtleTwo.forward(50);
        turtleOne.turn(330);
        turtleTwo.turn(30);
        turtleOne.forward(50);
        turtleTwo.forward(50);
        turtleOne.turn(330);
        turtleTwo.turn(30);
        turtleOne.forward(50);
        turtleTwo.forward(50);
        turtleOne.turn(330);
        turtleTwo.turn(30);
        turtleOne.forward(100);
        turtleTwo.forward(100);
        
    }
}